name: REPLACE_ME
description: REPLACE_ME
author: Ghalactic
inputs:
  REPLACE_ME:
    description: >-
      REPLACE_ME
    default: ""
outputs:
  REPLACE_ME:
    description: >-
      REPLACE_ME
branding:
  icon: REPLACE_ME
  color: REPLACE_ME
runs:
  using: docker
  image: Dockerfile
